language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ivanaleksandrov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ivanaleksandrov/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: docker-react
  env: DockerReact-env
  bucker_name: elasticbeanstalk-eu-central-1-275471398128
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY